// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpacXMeo0tFO46XKNRvZTdegR1uS-qIYY',
    appId: '1:458942725815:web:be92cd3d54f81a57815732',
    messagingSenderId: '458942725815',
    projectId: 'user-authentication-11e9a',
    authDomain: 'user-authentication-11e9a.firebaseapp.com',
    storageBucket: 'user-authentication-11e9a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkB-JQh2wNtoatPWFT2zuaaftGrMwpqO4',
    appId: '1:458942725815:android:371819fb2dd5c21d815732',
    messagingSenderId: '458942725815',
    projectId: 'user-authentication-11e9a',
    storageBucket: 'user-authentication-11e9a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJovojveEbLsqR7BC0ce9R76NjpjzDD-k',
    appId: '1:458942725815:ios:3c6cd3243f93f1d5815732',
    messagingSenderId: '458942725815',
    projectId: 'user-authentication-11e9a',
    storageBucket: 'user-authentication-11e9a.appspot.com',
    iosClientId: '458942725815-e0nqfpicbh8766d0acthm37u09bi0tck.apps.googleusercontent.com',
    iosBundleId: 'com.example.userAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJovojveEbLsqR7BC0ce9R76NjpjzDD-k',
    appId: '1:458942725815:ios:3c6cd3243f93f1d5815732',
    messagingSenderId: '458942725815',
    projectId: 'user-authentication-11e9a',
    storageBucket: 'user-authentication-11e9a.appspot.com',
    iosClientId: '458942725815-e0nqfpicbh8766d0acthm37u09bi0tck.apps.googleusercontent.com',
    iosBundleId: 'com.example.userAuth',
  );
}
